# Generated by Django 3.2.9 on 2021-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unprocessedaudio',
            name='testdata',
            field=models.BooleanField(default=False),
        ),
    ]
