# Generated by Django 3.2.9 on 2021-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_unprocessedaudio_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoSomething',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
