# Generated by Django 3.2.9 on 2021-12-03 02:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20211202_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocessedaudio',
            name='filedata',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='unprocessedaudio',
            name='filename',
            field=models.CharField(max_length=120),
        ),
    ]
