# Generated by Django 3.2.9 on 2021-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20211203_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocessedaudio',
            name='filedata',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
