# Generated by Django 3.2.9 on 2021-12-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_unprocessedaudio_filedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocessedaudio',
            name='filedata',
            field=models.FileField(upload_to=''),
        ),
    ]
