# Generated by Django 3.2.9 on 2021-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_remove_unprocessedaudio_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='unprocessedaudio',
            name='filedata',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
