# Generated by Django 3.2.9 on 2021-12-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_unprocessedaudio_filedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unprocessedaudio',
            name='filename',
        ),
    ]
