# Generated by Django 3.2.9 on 2021-12-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_remove_unprocessedaudio_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnprocessedAudio',
            new_name='AudioFile',
        ),
    ]
