# Generated by Django 3.2.9 on 2021-12-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0012_rename_unprocessedaudio_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name=0)),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audiofile')),
            ],
        ),
    ]
