# Generated by Django 4.0 on 2022-01-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0013_audiosample'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='denoisedfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='AudioSample',
        ),
    ]
