# Generated by Django 4.0 on 2022-01-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0014_audiofile_denoisedfile_delete_audiosample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='denoisedfile',
            new_name='denoisedFile',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='convolutionTime',
            field=models.CharField(default='', max_length=120),
        ),
    ]
