# Generated by Django 4.0 on 2022-01-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0015_rename_denoisedfile_audiofile_denoisedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audiofile')),
            ],
        ),
    ]
