# Generated by Django 4.0 on 2022-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0016_noiseclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseclip',
            name='title',
            field=models.CharField(default='noisecliptitle', max_length=120),
        ),
    ]
