# Generated by Django 4.0 on 2022-01-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0017_noiseclip_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referenceclip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='referencecliptitle', max_length=120)),
                ('audiofile', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
