# Generated by Django 4.0 on 2022-01-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0018_referenceclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseclip',
            name='parentAudio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='audio.audiofile'),
        ),
        migrations.AlterField(
            model_name='noiseclip',
            name='audiofile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
