# Generated by Django 4.0 on 2022-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0020_alter_noiseclip_parentaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='convolutionTime',
        ),
        migrations.AddField(
            model_name='noiseclip',
            name='endTime',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='noiseclip',
            name='startTime',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
