# Generated by Django 4.0 on 2022-01-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0021_remove_audiofile_convolutiontime_noiseclip_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseclip',
            name='call',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
