# Generated by Django 4.0 on 2022-01-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0022_noiseclip_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noiseclip',
            name='endTime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='noiseclip',
            name='startTime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
