# Generated by Django 4.0 on 2022-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0024_referenceclip_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
