# Generated by Django 4.0 on 2022-01-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0025_audiofile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseclip',
            name='referenceAudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.referenceclip'),
        ),
    ]
