# Generated by Django 4.0 on 2022-01-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0026_noiseclip_referenceaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noiseclip',
            name='call',
        ),
    ]
