# Generated by Django 4.0 on 2022-01-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0027_remove_noiseclip_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseclip',
            name='color',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='noiseclip',
            name='useAsReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noiseclip',
            name='endTime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='noiseclip',
            name='startTime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
