# Generated by Django 4.0 on 2022-02-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0029_animal_audioclip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.animal'),
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='use_as_ref',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
