# Generated by Django 4.0 on 2022-02-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0030_alter_audioclip_animal_alter_audioclip_use_as_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='reference_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.audioclip'),
        ),
    ]
