# Generated by Django 4.0 on 2022-02-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0031_alter_audioclip_reference_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='parent_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.audiofile'),
        ),
    ]
